### PR TITLE
Update data.node.yaml.version to 0.5 in configmap.yaml

### PR DESCRIPTION
**Pull request by jorda95225**

### CODE REVIEW

**Comment by fmassot** [comment]
Thanks @jorda95225 ! 

Can you also update the version "0.4" present also in comments? (where we give an example of an index config)

**Comment by jorda95225** [comment]
@fmassot No other ones have been found so far

**Comment by fmassot** [comment]
@jorda95225 you have some values there https://github.com/quickwit-oss/helm-charts/blob/main/charts/quickwit/values.yaml#L340-L373

Also, can you increment the hem chart version so that the test can pass?

**Comment by fmassot** [comment]
@jorda95225 thank you!

**Review by fmassot — APPROVED** [review]
LGTM

**Pull request merged**
